services:
  - type: web
    name: iim-lms-frontend
    env: static
    staticPublishPath: dist
    buildCommand: npm install --legacy-peer-deps && npm run build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
